name: portainer

services:
  portainer:
    image: portainer/portainer-ce:sts
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.portainer.rule=Host(`services.int.xbd.au`)
      - traefik.http.routers.portainer.middlewares=internal-only@file
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - web

volumes:
  portainer_data:
    external: true

networks:
  web:
    external: true
