name: registry

services:
  registry:
    image: registry:3.1.1
    container_name: registry
    restart: always
    environment:
      OTEL_TRACES_EXPORTER: none
    volumes:
      - /home/user/registry:/var/lib/registry
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.registry.rule=Host(`registry.baileys.dev`)
      - traefik.http.routers.registry.middlewares=registry-auth
      - traefik.http.middlewares.registry-auth.basicauth.users=${REGISTRY_HTPASSWD:?set in .env}
    networks:
      - web

networks:
  web:
    external: true
