name: ryot

services:
  ryot-db:
    image: postgres:18-alpine
    restart: unless-stopped
    container_name: ryot-db
    volumes:
      - postgres_storage:/var/lib/postgresql
    environment:
      - TZ=Australia/Melbourne
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  ryot:
    image: ghcr.io/ignisda/ryot:v10
    container_name: ryot
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
      - FRONTEND_URL=https://tracker.baileys.dev
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@ryot-db:5432/postgres
      - SERVER_ADMIN_ACCESS_TOKEN=${SERVER_ADMIN_ACCESS_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ryot.rule=Host(`tracker.baileys.dev`)
      - traefik.http.services.ryot.loadbalancer.server.port=8000

volumes:
  postgres_storage:
