# Repo: https://github.com/baely/infra
# Ref: d443b8052ff498104587bde4b108ae0a0f7e9581

services:
  coach:
    image: registry.baileys.dev/coach:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.coach.rule=Host(`coach.baileys.dev`)
      - traefik.http.services.coach.loadbalancer.server.scheme=h2c
      - traefik.http.services.coach.loadbalancer.server.port=8080
    env_file: ".env"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/user/github/infra/docker:/app/services"

networks:
  web:
    external: true
