# Repo: https://github.com/baely/infra
# Ref: 58dc597c9d4426fb147f7ff0c23e49781016d3cb

services:
  coach:
    image: registry.baileys.dev/coach:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.coach.rule=Host(`coach.baileys.dev`)
      - traefik.http.services.coach.loadbalancer.server.scheme=h2c
      - traefik.http.services.coach.loadbalancer.server.port=8080
    env_file: ".env"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
