on:
  workflow_call:
    inputs:
      service:
        description: "Service name"
        required: true
        type: string
      ref:
        description: "Git reference (branch, tag, or commit SHA)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Test
        run: |
          echo "Testing github: ${{ github.repository }}"
