name: Reusable workflow example

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - with:
        configuration-path: ${{ inputs.ref }}
      run: |
        echo "This is a reusable workflow example."
        echo "Configuration path: ${{ inputs.ref }}"
