apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: traefik
spec:
  selector:
    app: traefik
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      name: web
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
      name: websecure
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30880
      name: admin
