name: jumpbox

services:
  jumpbox:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: jumpbox
    restart: "no"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Australia/Sydney
    volumes:
      - webtop:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.jump.rule=Host(`webtop.xbd.au`)
      - traefik.http.routers.jump.middlewares=authentik-forward-auth@file
      - traefik.http.services.jump.loadbalancer.server.port=3000
      - traefik.docker.network=web
    networks:
      - web
      - pihole_dns
    dns:
      - 172.16.2.2

volumes:
  webtop:
    external: true

networks:
  web:
    external: true
  pihole_dns:
    external: true
