services:
  ip:
    image: registry.baileys.dev/ip:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.ip.rule=Host(`160.222.159.13`)
      - traefik.http.services.ip.loadbalancer.server.port=8080

networks:
  web:
    external: true
