global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  ssh:
    address: :22

  web:
    address: :80

  websecure:
    address: :443
    http:
      tls:
        certResolver: dev
        domains:
          - main: "kube.baileys.dev"
            sans:
              - "*.kube.baileys.dev"
          - main: "baileys.dev"
            sans:
              - "*.baileys.dev"
          - main: "baileys.app"
            sans:
              - "*.baileys.app"
          - main: "home.baileys.app"
            sans:
              - "*.home.baileys.app"
          - main: "lab.baileys.app"
            sans:
              - "*.lab.baileys.app"
          - main: "isbaileybutlerintheoffice.today"
          - main: "devhou.se"
            sans:
              - "*.devhou.se"
          - main: "baileyneeds.coffee"
          - main: "judd.devhou.se"
            sans:
              - "*.judd.devhou.se"
          - main: "baileys.page"
            sans:
              - "*.baileys.page"
          - main: "home.xbd.au"

  metrics:
    address: :8082

log:

api:
  insecure: true
  dashboard: true

ping:
  entryPoint: traefik

providers:
  docker:
    defaultRule: Host(`{{ normalize .Name }}.docker`)
    exposedByDefault: true
  file:
    filename: "/etc/traefik/conf.yaml"

http:
  services:
    portainer:
      server:
        port: 9443

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

tracing:
  otlp:
    http:
      endpoint: "http://jaeger:4318"

certificatesResolvers:
  dev:
    acme:
      email: "admin@baileys.dev"
      storage: "/acme/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
