# Repo: https://github.com/baely/txn
# Ref: bb99e557071928744f03519be01922466dba920d

services:
  txn:
    image: registry.baileys.dev/txn:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.txn.rule=Host(`baileyneeds.coffee`) || Host(`isbaileybutlerintheoffice.today`) || Host(`events.baileys.dev`)
      - traefik.http.services.txn.loadbalancer.server.port=8080
      - baileys.public.url=https://baileyneeds.coffee
      - baileys.public.title=Caffeine Tracker
      - baileys.public.description=Caffeine consumption based on location, electricity, and financial transactions
    env_file: ".env"
    volumes:
      - txn-data:/data
    networks:
      - web
      - pg

volumes:
  txn-data:

networks:
  web:
    external: true
  pg:
    external: true
