name: Deploy Service

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to use in the workflow'
        required: true
        type: string
      ref:
        description: 'Reference to use in the workflow'
        required: true
        type: string
    secrets:
      token:
        description: 'GitHub token for authentication'
        required: true

jobs:
  sync:
    name: Sync repository
    runs-on: ubuntu-latest
    steps:
    - name: Split owner/repo
      id: repo-name
      run: |
        OWNER=$(echo "${{ inputs.repository }}" | cut -d'/' -f1)
        REPO=$(echo "${{ inputs.repository }}" | cut -d'/' -f2)
        echo "OWNER=$OWNER" >> "$GITHUB_OUTPUT"
        echo "REPO=$REPO" >> "$GITHUB_OUTPUT"
        echo "Repository owner: $OWNER"
        echo "Repository name: $REPO"
    - name: Validate owner
      run: |
        if [ "${{ steps.repo-name.outputs.OWNER }}" != "baely" ]
        then
          echo "Invalid repository owner: ${{ steps.repo-name.outputs.OWNER }}"
          exit 1
        else
          echo "Valid repository owner: ${{ steps.repo-name.outputs.OWNER }}"
        fi
    - name: Checkout infra
      uses: actions/checkout@v4
      with:
        repository: baely/infra
        ref: main
    - name: Pull config
      env:
        GH_TOKEN: ${{ secrets.token }}
      run: |
      
        response=$(gh api "repos/${{ steps.repo-name.outputs.OWNER }}/${{ steps.repo-name.outputs.REPO }}/contents/main.go?ref=${{ inputs.ref }}")

        if [ $? -ne 0 ]; then
          echo "Failed to fetch main.go from repository"
          exit 1
        fi
       
        mkdir -p tmp/config
        echo "$response" | jq -r '.content' | base64 -d > tmp/config/main.go

        cat tmp/config/main.go
