name: Reusable workflow example

on:
  workflow_call:
  inputs:
    repository:
      description: 'Repository to use in the workflow'
      required: true
    ref:
      description: 'Reference to use in the workflow'
      required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "This is a reusable workflow example."
        echo "You can use this workflow in other workflows by calling it."
        echo "For example, you can call it in your main workflow file like this:"
        echo "jobs:"
        echo "  my_job:"
        echo "    uses: baely/infra/.github/workflows/reusable-workflow.yaml@v1"
        echo "    with:"
        echo "      repository: \${{ github.repository }}"
        echo "      ref: \${{ github.ref }}"
