name: Reusable workflow example

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to use in the workflow'
        required: true
        type: string
      ref:
        description: 'Reference to use in the workflow'
        required: true
        type: string

jobs:
  sync:
    name: Sync repository
    runs-on: ubuntu-latest
    steps:
    - name: Split owner/repo
      id: repo-name
      run: |
        echo "OWNER=$(echo "${{ inputs.repository }}" | cut -d'/' -f1)" >> "$GITHUB_OUTPUT"
        echo "REPO=$(echo "${{ inputs.repository }}" | cut -d'/' -f2)" >> "$GITHUB_OUTPUT"
        echo "Repository owner: ${{ steps.repo-name.outputs.OWNER }}"
        echo "Repository name: ${{ steps.repo-name.outputs.REPO }}"
    - name: Validate owner
      run: |
        if [ "${{ steps.repo-name.outputs.OWNER }}" != "baely" ]
        then
          echo "Invalid repository owner: ${{ steps.repo-name.outputs.OWNER }}"
          exit 1
        else
          echo "Valid repository owner: ${{ steps.repo-name.outputs.OWNER }}"
        fi
