name: Stage Infra
on:
  push:
    branches:
      - main
      - feat/cicd

jobs:
  stage:
    name: Stage Infra
    uses: baely/infra/.github/workflows/stage.yaml@bdd0764ce5bb18cb619f330ddb067650f16368fc
    with:
      repo: infra
      ref: ${{ github.sha }}
    secrets:
      INFRA_APP_ID: ${{ secrets.INFRA_APP_ID }}
      INFRA_APP_SECRET: ${{ secrets.INFRA_APP_SECRET }}
