name: Stage Infra
on:
  push:
    branches:
      - main
      - feat/cicd

jobs:
  stage:
    name: Stage Infra
    uses: baely/infra/.github/workflows/stage.yaml@0ba0e23b780673a4455287e40490265faaccd86d
    with:
      repo: infra
      ref: ${{ github.sha }}
    secrets:
      INFRA_APP_ID: ${{ secrets.INFRA_APP_ID }}
      INFRA_APP_SECRET: ${{ secrets.INFRA_APP_SECRET }}
