name: Stage Infra
on:
  push:
    branches:
      - main
      - feat/cicd

jobs:
  stage:
    name: Stage Infra
    uses: baely/infra/.github/workflows/stage.yaml@ef3b89d18733caedf1da4aadd06a08296ec63220
    with:
      repo: infra
      ref: ${{ github.sha }}
    secrets:
      INFRA_APP_ID: ${{ secrets.INFRA_APP_ID }}
      INFRA_APP_SECRET: ${{ secrets.INFRA_APP_SECRET }}
