name: Stage Infra
on:
  push:
    branches:
      - main
    paths:
      - tools/**

jobs:
  stage:
    name: Stage Infra
    uses: baely/infra/.github/workflows/stage.yaml@main
    with:
      repo: infra
      ref: ${{ github.sha }}
    secrets:
      INFRA_APP_ID: ${{ secrets.INFRA_APP_ID }}
      INFRA_APP_SECRET: ${{ secrets.INFRA_APP_SECRET }}

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs:
      - stage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: tools/go.mod
      - name: Run Builder
        env:
          COACH_AUTH_TOKEN: ${{ secrets.COACH_AUTH_TOKEN }}
        run: |
          cd tools
          go run ./cmd/coachassistant assemble \
          --repo infra \
          --ref ${{ github.sha }} \
          --image infra \
          --tag sha \
          --dockerfile tools/Dockerfile \
          --context tools
