name: Stage Infra
on:
  push:
    branches:
      - main
      - feat/cicd

jobs:
  stage:
    name: Stage Infra
    uses: baely/infra/.github/workflows/stage.yaml@69a4bf18b7096b0512288c735e5172bcc1837369
    with:
      repo: infra
      ref: ${{ github.sha }}
    secrets:
      INFRA_APP_ID: ${{ secrets.INFRA_APP_ID }}
      INFRA_APP_SECRET: ${{ secrets.INFRA_APP_SECRET }}
