name: Stage Infra
on:
  push:
    branches:
      - main
      - feat/cicd

jobs:
  stage:
    name: Stage Infra
    uses: baely/infra/.github/workflows/stage.yaml@82178bfc84920d605b66616876a41a41f8d07926
    with:
      repo: infra
      ref: ${{ github.sha }}
    secrets:
      INFRA_APP_ID: ${{ secrets.INFRA_APP_ID }}
      INFRA_APP_SECRET: ${{ secrets.INFRA_APP_SECRET }}
