name: Call a reusable workflow

on:
  pull_request:

jobs:
  call-workflow:
    uses: baely/infra/.github/workflows/deploy.yaml@workflow
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
