on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deployment
      uses: baely/infra/actions/deploy.yaml@workflow
      with:
        service: coffee
        ref: ${{ github.sha }}