name: traccar

services:
  traccar:
    image: traccar/traccar:6.14.5
    container_name: traccar
    restart: unless-stopped
    volumes:
      - /opt/traccar/traccar.xml:/opt/traccar/conf/traccar.xml
      - /opt/traccar/logs:/opt/traccar/logs
      - traccardb:/opt/traccar/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.traccar-web.rule=Host(`traccar.int.xbd.au`)
      - traefik.http.routers.traccar-web.service=traccar-web
      - traefik.http.services.traccar-web.loadbalancer.server.port=8082
      - traefik.http.routers.traccar.rule=Host(`traccar.xbd.au`)
      - traefik.http.routers.traccar.service=traccar
      - traefik.http.services.traccar.loadbalancer.server.port=5055
      - baileys.public.url=https://traccar.int.xbd.au
      - baileys.public.title=Traccar
      - baileys.public.description=Device tracking
    networks:
      - web
      - pg

volumes:
  traccardb:
    external: true

networks:
  web:
    external: true
  pg:
    external: true
